name: Build and Deploy create-user to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/create-user:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/create-user:${{ env.IMAGE_TAG }}

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy container on EC2 from Docker Hub (latest tag)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF

            if ! command -v docker &> /dev/null; then
              echo "🔧 Instalando Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker \$USER
            else
              echo "✅ Docker ya está instalado."
            fi

            echo "${{ secrets.ENV_FILE }}" > ~/create_user.env

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/create-user:${{ env.IMAGE_TAG }}

            sudo docker rm -f create-user || true

            sudo docker run -d \
              --name create-user \
              --env-file ~/create_user.env \
              -p 3002:3002 \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/create-user:${{ env.IMAGE_TAG }}

          EOF